### ISSUE TITLE
What ML framework did you use?

### ISSUE THREAD

**Issue by todeveloper21** [vladimirwest/OpenVINO_Face_Anti-Spoofing#1]
Thank you for your great work!
I want to know which framework of ML you used.
tensorflow? or Pytorch?
Can you share original model before converting to OpenVINO model?

**Comment by vladimirwest** [comment]
Hi, @zhenzhen823!
Pytorch was used for the original model.
I have updated the repo with **original_model** folder that contains model weights and simple images prediction script.

**Comment by todeveloper21** [comment]
Thank you a lot.
